# Generated by Django 5.1.2 on 2025-08-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Study', 'Study'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('purple', 'Purple')], default='yellow', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='is_checklist',
            field=models.BooleanField(default=False),
        ),
    ]
